sonar.projectKey=CTSE_Assignment01-frontend
sonar.organization=eshmika
sonar.projectName=Frontend
sonar.projectVersion=1.0

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.test.js,**/*.test.ts,**/*.spec.js,**/*.spec.ts
sonar.exclusions=**/node_modules/**,**/.next/**,**/*.config.js,**/*.config.ts

sonar.javascript.node.maxspace=4096
sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.typescript.node.maxspace=4096
sonar.typescript.lcov.reportPaths=coverage/lcov.info