version: "3.8"

services:
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./api-gateway/.env
    depends_on:
      - auth-service
      - catalog-service
      - order-service
      - payment-service
    networks:
      - microservices-network
    healthcheck:
      test:
        ["CMD", "wget", "-q", "-O-", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    env_file:
      - ./auth-service/.env
    networks:
      - microservices-network
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "-q",
          "-O-",
          "http://localhost:8081/auth/actuator/health/liveness",
        ]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s

  catalog-service:
    build:
      context: ./catalog-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    env_file:
      - ./catalog-service/.env
    depends_on:
      - auth-service
    networks:
      - microservices-network
    healthcheck:
      test:
        ["CMD", "wget", "-q", "-O-", "http://localhost:8082/actuator/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s

  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    env_file:
      - ./order-service/.env
    depends_on:
      - auth-service
      - catalog-service
    networks:
      - microservices-network
    healthcheck:
      test:
        ["CMD", "wget", "-q", "-O-", "http://localhost:8083/actuator/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s

  payment-service:
    build:
      context: ./payment-service
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    env_file:
      - ./payment-service/.env
    depends_on:
      - auth-service
      - order-service
    networks:
      - microservices-network
    healthcheck:
      test:
        ["CMD", "wget", "-q", "-O-", "http://localhost:8084/actuator/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s

networks:
  microservices-network:
    driver: bridge
