sonar.projectKey=CTSE_Assignment01-order-service
sonar.organization=eshmika
sonar.projectName=Order Service
sonar.projectVersion=1.0

sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.java.test.binaries=target/test-classes

sonar.junit.reportPaths=target/surefire-reports/*.xml
sonar.jacoco.reportPaths=target/site/jacoco/jacoco.xml

sonar.exclusions=**/target/**,**/node_modules/**,**/*.js,**/*.html,**/*.css
sonar.test.inclusions=**/*Test.java,**/*Tests.java
sonar.coverage.exclusions=**/config/**,**/entity/**,**/dto/**,**/exception/**

sonar.java.source=17
sonar.java.target=17